### PR TITLE
Ci issues with commits

### LINKED ISSUE #401: Travis builds broken Error: Command failed: /bin/sh -c git log fatal: bad default revision 'HEAD'
We are getting errors in Travis in the commit tests. Looks like the problem might be reading the git logs or with commits. Might have been a git config change on travis. 

https://travis-ci.org/commitizen/cz-cli/jobs/183566039

I have a branch here: https://github.com/commitizen/cz-cli/tree/ci-issues-with-commits

### PR DESCRIPTION
**Pull request by jimthedev**
Closes #401.

### CODE REVIEW

File: src/git/log.js [hunk 1]
```diff
@@ -11,6 +11,7 @@ function log(repoPath, done) {
     cwd: repoPath
   }, function(error, stdout, stderr) {
     if (error) {
+      throw new Error(error);
```
Comment (LinusU) [inline src/git/log.js]: also, this makes the line below (`done();`) unreachable since a `throw` interrupts the execution of the function

Comment (jimthedev) [inline src/git/log.js]: I agree it already is an instance of Error. I'll change that.

The reason I decided to throw here is that this is actually fatal. If we can't do git log, we can't check if the commit worked and the process needs to throw so that our tests can return the correct error code and output an actual error to stderr. It is only used in test and was silently failing in the previous configuration.

Comment (jimthedev) [inline src/git/log.js]: Also, we could certainly benefit from re-writing the codebase to use (err, cb) style 😸
